apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: pipelines-efs-volume
      persistentVolumeClaim:
        claimName: pipelines-efs
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.11.2-2
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: node
    image: circleci/node:14.18.1-browsers
    resources:
      requests:
        cpu: 1.2
        memory: 2.5Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    volumeMounts:
      - mountPath: "/mnt/data"
        name: pipelines-efs-volume
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.1
        memory: 256Mi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
